Rebuild against libnetcdf 4.8
AnacondaRecipes/vtk-feedstock pull request #13
Opened 2022-01-24 14:41 UTC by tobijk

2022-02-22 19:32 UTC, varlackc reviewed
missing git `dev_url` this seems to be a potential source for development

https://gitlab.kitware.com/vtk/vtk


might also need a `doc_url`


license needs to be spdx compliant, we probably should use `BSD-3-clause`

need to also add the `license_family`

2022-02-23 13:31 UTC, tobijk commented
I couldn't find a copy of the documentation online that corresponds to this exact version, thus not including a doc_url.

2022-02-23 13:55 UTC, tobijk commented on recipe/meta.yaml
> +  skip: True  # [win32 or s390x or ppc64le]
Hm, is this correct now? Thanks!

2022-02-23 13:57 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True  # [win32 or s390x or ppc64le]
We need to check if prefect or concourse will create all needed artifacts

2022-02-23 14:16 UTC, tobijk commented on recipe/meta.yaml
> +  skip: True  # [win32 or s390x or ppc64le]
Ok, I will check the build logs, when everything went through (*if* everything goes through) :)

2022-02-23 15:06 UTC, varlackc reviewed
As far as I could see, everything else in the recipe seems to be fine, as soon as the packages build properly in prefect we should be good to go.

2022-02-23 18:46 UTC, varlackc approved these changes

2022-02-23 19:38 UTC, tobijk commented on recipe/meta.yaml
> +  skip: True  # [win32 or s390x or ppc64le]
* linux-64:<br/>3.7 - 3.8 - 3.9
* linux-aarch64:<br/>3.7 - 3.8 - 3.9
* osx-64:<br/>3.7 - 3.8 - 3.9
* osx-arm64:<br/>3.8 - 3.9

Looks right to me.

2022-02-23 19:53 UTC, ScottBailey commented on recipe/meta.yaml
> +  doc_url: https://github.com/Kitware/VTK/tree/v9.0.3/Documentation/Doxygen
I believe `doc_url` should be one of the following or possibly all:
- https://vtk.org/documentation/
- https://www.vtk.org/doc/nightly/html/
- https://www.vtk.org/files/release/9.0/vtkDocHtml-9.0.3.tar.gz. 

But that last one is a maintenance challenge. Maybe if we put some jinja macros in it? The problem here is that we can't just use {{ version }} as it's major.minor.patch. Though I've seen jinja that sets major.minor from the full semantic version. 

Unfortunately, we don't have version specific doc links at anaconda.org, though I think we can do lists. 

And `doc_src_url` should be one of the following?
- https://github.com/Kitware/VTK/tree/v{{ version }}/Documentation/Doxygen
- https://gitlab.kitware.com/vtk/vtk/-/tree/master/Documentation
- https://gitlab.kitware.com/vtk/vtk/-/tree/v{{ version }}/Documentation

2022-02-23 20:17 UTC, ScottBailey commented on recipe/use-std-atomic-instead-of-tbb-atomic.patch
> +
I don't think this patch needs to be longer than this because:
1. `tbb::atomic::operator T()` is essentially the same as `std::atomic::operator T()` which is essentially the same as `std::atomic::load()`. 
2 `tbb::atomic::operator=(T)` is essentially the same as `std::atomic::operator=(T)` which is essentially the same as `std::atomic::store(T)`.

It doesn't hurt, but a shorter patch is easier to maintain.

2022-02-23 20:31 UTC, ScottBailey requested changes
`doc_url` (in `meta.yaml`) should be corrected.
Atomic patch file *could* be downscoped, but that shouldn't hold up the package.

2022-02-24 08:22 UTC, tobijk commented on recipe/meta.yaml
> +  doc_url: https://github.com/Kitware/VTK/tree/v9.0.3/Documentation/Doxygen
I don't think it is right to link to the nightly documentation, it should be documentation for the exact version. I'm fine with using the tarball.

2022-02-24 09:36 UTC, tobijk commented on recipe/use-std-atomic-instead-of-tbb-atomic.patch
> +
I'm not a C++ expert, but I basically ran into this:

https://stackoverflow.com/questions/27314485/use-of-deleted-function-error-with-stdatomic-int

Hence all the load and stores. Maybe a few of them are really not necessary, but some definitely are.

2022-03-01 06:29 UTC, merged